name: chat
on:
  push:
    branches: [ chat ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: chat
        shell: bash 
        run: |
          TGT='amd64';  _KIWI_FILE_=kiwiirc_20.05.24.1_linux_$TGT  \
          && wget https://kiwiirc.com/downloads/$_KIWI_FILE_.zip \
          && unzip $_KIWI_FILE_.zip \
          && rm $_KIWI_FILE_.zip \
          && mv kiwiirc_linux_$TGT kiwiirc \
          && cd kiwiirc \
          && mv config.conf.example config.conf \
          && sed -i 's/port = 80/port = 8080/g' config.conf \
          && sed -i 's/hostname = "irc.kiwiirc.com"/hostname = "127.0.0.1"/g' config.conf \
          && cd .. \
          && TGT='x86_64'; _ERGO_FILE_=ergo-2.9.1-linux-$TGT \
          && wget https://github.com/ergochat/ergo/releases/download/v2.9.1/$_ERGO_FILE_.tar.gz \
          && tar xf $_ERGO_FILE_.tar.gz \
          && rm $_ERGO_FILE_.tar.gz \
          && mv $_ERGO_FILE_ ergo \
          && cd ergo \
          && mv default.yaml ircd.yaml \
          && sed -i 's/"\[::1\]:6667":/#"\[::1\]:6667":/g' ircd.yaml \
          && chmod u+x ergo 
          ./ergo mkcerts || echo
          ./ergo run & 
          cd ../kiwiirc
          ./kiwiirc &
          mkdir ../tunnelme
          cd ../tunnelme
          which npx npm
          npx localtunnel --port 8000 2>&1 | tee info.txt &
      - name: info
        shell: bash 
        run: |
          cd ../tunnelme
          ls -l
          cat *.txt
      - name: info2
        shell: bash 
        run: |
          cd ../tunnelme
          ls -l
          cat *.txt
          tail -f info.txt
